from random import randint

n=randint(1,100)
guesses=1
a=0
print
while(a != n):
    a=int(input("Guess a number :"))
    if(a > n):
        print("Lower number please")
        guesses += 1
    elif( a < n):
        print("Higher number please")
        guesses += 1
print(f"DONE ! You guess the number {n} in {guesses} attempts .")

# This code is generated by chatGPT
# import time
# from random import randint

# leaderboard = {}

# def give_hint(number):
#     hints = []
#     if number % 2 == 0:
#         hints.append("The number is EVEN.")
#     else:
#         hints.append("The number is ODD.")

#     for i in [3, 5, 7]:
#         if number % i == 0:
#             hints.append(f"The number is divisible by {i}.")
#             break

#     return hints

# def play_game(player_name):
#     print("\n🎮 Welcome to the Number Guessing Game, {}!".format(player_name))
#     print("Choose a difficulty level:")
#     print("1. Easy (1–50, 10 attempts)")
#     print("2. Medium (1–100, 7 attempts)")
#     print("3. Hard (1–200, 5 attempts)")

#     difficulty = input("Enter your choice (1/2/3): ")

#     if difficulty == "1":
#         max_number = 50
#         max_attempts = 10
#     elif difficulty == "2":
#         max_number = 100
#         max_attempts = 7
#     elif difficulty == "3":
#         max_number = 200
#         max_attempts = 5
#     else:
#         print("Invalid choice. Defaulting to Medium.")
#         max_number = 100
#         max_attempts = 7

#     number = randint(1, max_number)
#     attempts = 0
#     guess = None
#     start_time = time.time()

#     # Uncomment for testing:
#     # print(f"(DEBUG) Number is {number}")

#     while guess != number and attempts < max_attempts:
#         try:
#             guess = int(input(f"\nGuess a number (1 to {max_number}): "))
#         except ValueError:
#             print("Please enter a valid integer.")
#             continue

#         attempts += 1

#         if guess == number:
#             end_time = time.time()
#             time_taken = round(end_time - start_time, 2)
#             score = (max_attempts - attempts + 1) * 10

#             print(f"\n🎉 Correct! You guessed the number {number} in {attempts} attempts.")
#             print(f"⏱️ Time taken: {time_taken} seconds")
#             print(f"🏆 Score: {score} points")

#             leaderboard[player_name] = {
#                 "score": score,
#                 "time": time_taken,
#                 "attempts": attempts
#             }
#             break
#         elif guess > number:
#             print("Too high!")
#         else:
#             print("Too low!")

#         remaining = max_attempts - attempts
#         if remaining > 0:
#             print(f"🔁 Attempts left: {remaining}")

#             # Give hint after 3 wrong attempts
#             if attempts == 3:
#                 print("💡 Hint:", " ".join(give_hint(number)))
#         else:
#             print(f"\n❌ No attempts left! The number was {number}. Better luck next time!")

# def display_leaderboard():
#     if not leaderboard:
#         print("\n📭 No scores yet.")
#         return

#     print("\n📋 Leaderboard:")
#     sorted_players = sorted(leaderboard.items(), key=lambda x: (-x[1]['score'], x[1]['time']))
#     for i, (name, stats) in enumerate(sorted_players, start=1):
#         print(f"{i}. {name} — Score: {stats['score']}, Time: {stats['time']}s, Attempts: {stats['attempts']}")

# # Main loop
# while True:
#     player = input("\nEnter your name: ").strip()
#     play_game(player)

#     again = input("\nDo you want to play again? (y/n): ").lower()
#     if again != 'y':
#         break

# display_leaderboard()
# print("\nThanks for playing! 👋")

